name: Analyysi ja Raportointi

on:
  workflow_dispatch:
  push:
    paths:
      - 'veikkausliiga_tilastot.json'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Asenna Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Asenna riippuvuudet
      run: |
        pip install pandas matplotlib numpy
        
    - name: Luo tarvittavat kansiot
      run: |
        mkdir -p utils reports
        touch utils/team_aliases.json
        
    - name: Suorita analyysi
      run: python veikkausliiga_analyysi.py
      
    - name: Tallenna muutokset
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add reports/ veikkausliiga_elo_historia.json
        git commit -m "Automaattinen analyysipäivitys"
        git push
