name: Analysoi ja Päivitä

on:
  workflow_dispatch:
  push:
    paths:
      - 'veikkausliiga_tilastot.json'

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Asenna Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Asenna riippuvuudet
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib
    
    - name: Suorita analyysi
      run: |
        mkdir -p reports
        python veikkausliiga_analyysi.py
    
    - name: Commit ja push muutokset
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git add reports/ veikkausliiga_elo_historia.json
        git commit -m "Automaattinen analyysipäivitys"
        git push
